project:
  type: website
  output-dir: docs
  repo-url: https://mayert1.github.io/Quarto_Website/

website:
  title: "Quarto_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true